services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/webchat
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"